import outputs from '../amplify_outputs.json';
import { Amplify } from 'aws-amplify';

// Configure Amplify using outputs generated by `npx ampx outputs`.
// This placeholder file will be replaced after backend deploy.
Amplify.configure(outputs);

export default Amplify;

